---
title: "Psicologia della personalità e delle differenze individuali"
subtitle: "Materiali integrativi al corso"
author: "Tommaso Feraco"
#include-in-header: assets/header.html
format: 
  html:
    self-contained: true
    toc: true   
    toc-depth: 3 
    toc-expand: 3 
    code-fold: false 
    message: false
#    css: "assets/custom.css"
editor: visual
---

Il corso di Psicologia della Personalità e delle Differenze Individuali sarà tenuto da Tommaso Feraco e Giovanna Mioni.

## Date e aule

| Giorno  | Time        | Room |
|---------|-------------|------|
| Lunedì  | 10:30-12:30 | T4   |
| Venerdì | 10:30-12:30 | T4   |

## Informazioni sul corso

Questo corso è parte integrante del corso di laurea in [Scienze psicologiche dello sviluppo, della personalità e delle relazioni interpersonali](https://www.psicologia.unipd.it/offerta-didattica/corsi-di-laurea/?tipo=L&ordinamento=2023&key=PS2295).

## Materiali

Puoi trovare qui i materiali aggiuntivi per il corso:

-   **Personality skills** - [html](https://feracotommaso.github.io/Personality-and-individual-differences/chapters/personalitySkills.html){target="_blank"} <!--# - pdf -->
-   **Intelligenza e *g-factor*** - NA

## Risultati

Puoi trovare qui le slide con i risultati visti in classe:

-   **Big Five e EPI** - [2025](https://feracotommaso.github.io/Personality-and-individual-differences/results/2025/1.Risultati.html)

------------------------------------------------------------------------

::: {style="font-size:11px;"}
GitHub repository associated to the present course website: <https://github.com/feracotommaso/Personality-and-individual-differences>

Many thanks to Filippo Gambarota and Enrico Toffalini for sharing their expertise in using GitHub, Quarto, and creating GitHub Pages websites.
:::
